name: Rust CI

on:
  push:
    branches: [main]
    paths: ['cli/**/*', 'native/**/*', 'Cargo.toml', 'Cargo.lock']
  pull_request:
    paths: ['cli/**/*', 'native/**/*', 'Cargo.toml', 'Cargo.lock']

jobs:
  test-cli:
    name: Test CLI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - name: Install CI dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libdbus-1-dev libssl-dev gnome-keyring
        working-directory: .

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Start gnome-keyring
        run: gnome-keyring-daemon --components=secrets --daemonize --unlock <<< 'foobar'
        working-directory: .

      - name: Run CLI cargo test
        env:
          RUST_LOG: debug
        run: cargo test --all -- --test-threads=1

  test-native:
    name: Test PDF Extractor
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./native/pdf_extractor
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run PDF Extractor cargo build
        run: cargo build

  formatting:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt Check for CLI
        run: cargo fmt --all --check
        working-directory: ./cli

      - name: Run rustfmt Check for PDF Extractor
        run: cargo fmt --all --check
        working-directory: ./native/pdf_extractor
